### ISSUE TITLE
In about this repo

### ISSUE THREAD

**Issue by kry008** [recallwei/wiki#37]
[bruce-wiki.vercel.app](https://bruce-wiki.vercel.app/)
```
404: NOT_FOUND  
Code: DEPLOYMENT_NOT_FOUND  
ID: arn1::ck5mz-1659287065013-d1dde01549e4  
```

**Comment by recallwei** [comment]
I changed my domain a few days ago and forgot to update this link in the repository. Try this: https://wiki.bruceworld.top/
